[pytest]
minversion = 7.0
addopts = -ra -q --strict-markers
testpaths =
    tests
pythonpath = .
markers =
    unit: Модульные тесты
    validation: Тесты модуля валидации
    integration: Интеграционные тесты

    [pytest]

filterwarnings =
    # По умолчанию превращаем предупреждения в ошибки
    error
    # Игнорируем устаревания сторонних библиотек (FastAPI / Starlette)
    ignore::starlette.exceptions.StarletteDeprecationWarning
    ignore::DeprecationWarning:starlette.*
    ignore::DeprecationWarning:httpx.*