from __future__ import annotations

import pathlib
from typing import List

from ..domain.models import DocPage, Section, Version
from ai_framework.rendering import SeoContext, SeoInjector, JinjaTemplateRenderer


class DocsRenderer:
    """
    Showcase-local renderer for docs_site.

    Owns docs-specific URL semantics:
        /v/{version}/
        /v/{version}/{section}/
        /v/{version}/{section}/{page}/

    Uses only framework rendering primitives.
    """

    def __init__(self, templates_dir: pathlib.Path | str | None = None):
        if templates_dir is None:
            here = pathlib.Path(__file__).resolve()
            candidate = here.parent.parent / "templates"
            templates_dir = (
                candidate
                if candidate.exists()
                else pathlib.Path("showcases/docs_site/templates")
            )

        self.templates_dir = pathlib.Path(templates_dir)
        self.template_renderer = JinjaTemplateRenderer(self.templates_dir)
        self.seo_injector = SeoInjector()

    def _seo_obj(
        self,
        doc_or_dict,
        title_fallback: str = "Docs",
    ) -> SeoContext:
        if hasattr(doc_or_dict, "to_dict"):
            data = doc_or_dict.to_dict()
        elif isinstance(doc_or_dict, dict):
            data = doc_or_dict
        else:
            data = {}

        return SeoContext.normalize(
            data,
            title_fallback=title_fallback,
        )

    def _inject(
        self,
        html: str,
        seo: SeoContext,
    ) -> str:
        return self.seo_injector.ensure_seo(html, seo)

    @staticmethod
    def _page_links(docs: List[DocPage], urls: dict[str, str]) -> list[dict[str, str]]:
        return [
            {
                "title": doc.title,
                "url": urls[str(doc.id)],
            }
            for doc in docs
            if str(doc.id) in urls
        ]

    def render_doc(
        self,
        doc: DocPage,
        section: Section | None = None,
        version: Version | None = None,
        page_url: str = "",
    ) -> str:
        seo = self._seo_obj(doc, doc.title)

        context = {
            "doc": doc,
            "page": doc,
            "section_name": section.name if section else "",
            "version_name": version.name if version else "",
            "page_url": page_url,
            "seo_title": seo.seo_title,
            "seo_description": seo.seo_description,
            "og_title": seo.og_title,
            "og_description": seo.og_description,
            "canonical_url": seo.canonical_url,
        }

        try:
            html = self.template_renderer.render(
                "page.html",
                context,
            )
            return self._inject(html, seo)
        except Exception:
            try:
                html = self.template_renderer.render(
                    "doc_page.html",
                    context,
                )
                return self._inject(html, seo)
            except Exception:
                return (
                    "<!doctype html>"
                    "<html>"
                    "<head>"
                    '<meta charset="utf-8">'
                    f"<title>{seo.seo_title}</title>"
                    "</head>"
                    "<body>"
                    f"<header><h1>{doc.title}</h1></header>"
                    f"<main><article>{doc.content}</article></main>"
                    f'<footer><a href="{page_url}">Permalink</a></footer>'
                    "</body>"
                    "</html>"
                )

    def render_index(
        self,
        docs: List[DocPage],
        page_urls: dict[str, str],
    ) -> str:
        seo = SeoContext.normalize(
            {
                "title": "Documentation",
                "seo_title": "Documentation",
                "seo_description": f"{len(docs)} pages",
                "og_title": "Documentation",
            },
            title_fallback="Documentation",
        )

        context = {
            "doc": {"title": "Documentation"},
            "docs": docs,
            "pages": docs,
            "page_links": self._page_links(docs, page_urls),
        }

        try:
            html = self.template_renderer.render(
                "index.html",
                context,
            )
            return self._inject(html, seo)
        except Exception:
            items = "".join(
                f'<li><a href="{page_urls[str(doc.id)]}">{doc.title}</a></li>'
                for doc in docs
                if str(doc.id) in page_urls
            )
            return (
                "<!doctype html><html><head>"
                '<meta charset="utf-8">'
                "<title>Documentation</title>"
                "</head><body>"
                "<header><h1>Documentation</h1></header>"
                f"<main><ul>{items}</ul></main>"
                "<footer><p>Generated by docs_site</p></footer>"
                "</body></html>"
            )

    def render_section(
        self,
        section: Section,
        version: Version,
        docs: List[DocPage],
        page_urls: dict[str, str],
    ) -> str:
        seo = SeoContext.normalize(
            {
                "title": section.name,
                "seo_title": section.name,
            },
            title_fallback=section.name,
        )

        context = {
            "doc": {"title": section.name},
            "section_name": section.name,
            "version_name": version.name,
            "slug": section.slug,
            "docs": docs,
            "pages": docs,
            "page_links": self._page_links(docs, page_urls),
        }

        try:
            html = self.template_renderer.render(
                "section.html",
                context,
            )
            return self._inject(html, seo)
        except Exception:
            items = "".join(
                f'<li><a href="{page_urls[str(doc.id)]}">{doc.title}</a></li>'
                for doc in docs
                if str(doc.id) in page_urls
            )
            return (
                "<!doctype html><html><head>"
                '<meta charset="utf-8">'
                f"<title>{section.name}</title>"
                "</head><body>"
                f"<header><h1>{section.name}</h1>"
                f"<p>{version.name}</p></header>"
                f"<main><ul>{items}</ul></main>"
                "<footer><p>Generated by docs_site</p></footer>"
                "</body></html>"
            )

    def render_version(
        self,
        version: Version,
        docs: List[DocPage],
        page_urls: dict[str, str],
    ) -> str:
        seo = SeoContext.normalize(
            {
                "title": version.name,
                "seo_title": version.name,
            },
            title_fallback=version.name,
        )

        context = {
            "doc": {"title": version.name},
            "version_name": version.name,
            "slug": version.slug,
            "docs": docs,
            "pages": docs,
            "page_links": self._page_links(docs, page_urls),
        }

        try:
            html = self.template_renderer.render(
                "version.html",
                context,
            )
            return self._inject(html, seo)
        except Exception:
            items = "".join(
                f'<li><a href="{page_urls[str(doc.id)]}">{doc.title}</a></li>'
                for doc in docs
                if str(doc.id) in page_urls
            )
            return (
                "<!doctype html><html><head>"
                '<meta charset="utf-8">'
                f"<title>{version.name}</title>"
                "</head><body>"
                f"<header><h1>{version.name}</h1></header>"
                f"<main><ul>{items}</ul></main>"
                "<footer><p>Generated by docs_site</p></footer>"
                "</body></html>"
            )

    def render_sitemap(self, paths: List[str]) -> str:
        # Try to use template if available, fallback to manual
        try:
            html = self.template_renderer.render(
                "sitemap.xml",
                {"paths": paths, "sitemap_paths": paths},
            )
            # if template rendered empty urls, fallback to manual
            if "<url>" in html or "<loc>" in html:
                return html
        except Exception:
            pass
        urls = "\n".join(f" <url><loc>{path}</loc></url>" for path in paths)
        return (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"{urls}\n"
            "</urlset>\n"
        )
